coverage:
  status:
    project:
      default:
        target: 80%
        threshold: 1%
        paths:
          - "generator"
    patch:
      default:
        target: 80%
        threshold: 1%
        paths:
          - "generator"
ignore:
  - "examples"
