coverage:
  status:
    project:
      default:
        target: 80%
        threshold: 1%
        paths:
          - "runner"
    patch:
      default:
        target: 80%
        threshold: 1%
        paths:
          - "runner"

