file_extension: fbs
type_config:
  float: float32
  double: float64
  int32: int32
  int64: int64
  uint32: uint32
  uint64: uint64
  sint32: int32
  sint64: int64
  fixed32: uint32
  fixed64: uint64
  sfixed32: int32
  sfixed64: int64
  bool: bool
  string: string
  bytes: "[ubyte]"
case_config:
  file_name: lower_snake
  package: UpperCamel
  import: UpperCamel
  enum_name: UpperCamel
  enum_value_name: UpperCamel
  message_name: UpperCamel
  field_name: lower_snake
metadata_file_name: metadata
package_separator: .
one_file_per_package: false
default_package_file_name: _
field_name_override:
  enum: enum_
ignored_files:
  - options_impl.proto
ignored_imports:
  - protox.proto
  - fbs.proto
field_relative_parent_prefix: null
generated_header: null
scripted:
  indent_char: Space
  scope:
    open: "{"
    close: "}"
    indent: 4
    open_on_new_line: false
overlays:
  by_target:
    # File.
    flatbuffers.proto:
      attributes:
        - priority
      identifier: ABCD
      extension: data
      root_type: Table
    # Enum.
    fbs.ByteEnum:
      type: byte
    fbs.LongEnum:
      type: long
    # Message.
    fbs.Union:
      type: union
    fbs.Struct:
      type: struct
    # Field.
    fbs.Table.bool_value:
      default: true
    fbs.Table.byte_value:
      type: byte
    fbs.Table.ubyte_value:
      type: ubyte
    fbs.Table.short_value:
      type: short
    fbs.Table.ushort_value:
      type: ushort
    fbs.Table.i32_value:
      default: 1111
    fbs.Table.f32_value:
      default: 1111.2222
    fbs.Table.value_with_attrs_and_default:
      default: 1234
      attributes:
        - "priority: 1"
        - deprecated
