[package]
name = "cli"
version = "0.1.0"
edition = "2018"

[[bin]]
name = "idlx"
path = "src/main.rs"

[dependencies]
runner = { path = "../runner" }
anyhow = "1.0"

[dev-dependencies]
tempfile = "3.2"
serde_json = "1.0"
