[package]
name = "example-usage"
version = "0.1.0"
edition = "2018"

build = "build.rs"

[[bin]]
name = "idlx-examples"
path = "src/main.rs"

[build-dependencies]
generator = { path = "../generator" }
