name: coverage

on:
  push:
    paths-ignore:
      - "README.md"
      - "codecov.yml"
      - "proto_options"

jobs:
  test:
    name: coverage

    runs-on: ubuntu-latest

    container:
      image: xd009642/tarpaulin:develop-nightly
      options: --security-opt seccomp=unconfined

    steps:
      - name: Setup protoc
        uses: arduino/setup-protoc@v1.1.2

      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup git for submodule pull through cargo
        shell: bash
        run: git config --global url."https://github.com/".insteadOf "git@github.com:"

      - name: Generate code coverage
        run: cargo +nightly tarpaulin --verbose --all-features --workspace --timeout 120 --out Xml

      - name: Upload to codecov.io
        uses: codecov/codecov-action@v1
        with:
          fail_ci_if_error: true
