name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build-and-test:
    name: Rust project
    runs-on: ubuntu-latest
    steps:
      - name: Setup protoc
        uses: arduino/setup-protoc@v1.1.2

      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
      - uses: actions-rs/cargo@v1
        with:
          command: build
          args: --release --workspace --verbose --all-features
